basePath: /
definitions:
  models.User:
    properties:
      email:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Đây là một API được tạo tự động bởi CRUD Generator.
  title: CRUD Generator API
  version: "1.0"
paths:
  /users:
    post:
      consumes:
      - application/json
      description: Tạo một user mới
      parameters:
      - description: Thông tin user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Tạo một user mới
      tags:
      - users
  /users/{id}:
    get:
      consumes:
      - application/json
      description: Lấy thông tin user bằng ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Lấy thông tin user bằng ID
      tags:
      - users
swagger: "2.0"
